# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59480f1c4314603c312fdefcf928f85bd7025bbcf1314ed97f917122fce0c3f00891b0cf54ec53e542e8f4d609b57df559600753eb444a33a86a2042fff6e86f

test:
  secret_key_base: ba0d01b0e51269a55a7759c65a5faf22c27d83e4bd6d0a63632dfb6aca950cf9bb502e49350dd9fccbd9b5d2a118493245268804d9eff2ea8fb65a3a8cc99348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
